# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 314d6a5023d2256ffdb039c02ee4e08b58e10f35f944c0aabdf2125604c2df9cca7b4f4b7e04de779bcb67c27047e76baac59c0b115be151649a23d51211614f

test:
  secret_key_base: 918f5c92fbc4fc8b4218abff87c485b42d8eb92e6b705b8804581cde788e6f91f75c6763d582b81ad917502cad3257031b740fd7084e7a11d6f3542dc80f6fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
